# =================================================================================================================================
# Stages to be executed, each stage is a collection of jobs pointing to the stage
# =================================================================================================================================

stages:
  - build
  - short_runs

# global paths to be kept between jobs
cache:
  paths:
  - build__intel

# =================================================================================================================================
# Stage "build"
# v>9 artifacts: name: "${CI_PIPELINE_ID}_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
#
# SHORT SYNTAX EXPLANATIONS FOR THE JOB, FOR DETAILS VISIT:    ===> https://docs.gitlab.com/ce/ci/yaml/   <===
# "stage:"         makes the job part of a stage defined above
# "tags:"          selects the runner
# "only:"          restricts the execution of the job to a git branch or tag
# "before_script:" shell commands to be executed before the main script. 
# "script:"        shell commands for the test. If a shell command exits with >0, the job is marked as "failed", else as "passed".
#                  commands after a failing one are not executed anymore!
# "after_script:"  shell commands after passed OR failed script. Careful, the current directory is always the root of the repo!
# "artifacts:"     keep data from the job which is uploaded to gitlab.com. You really should set a duration to expiration.
#                  "when:" can be either on_failure, on_success or always
# =================================================================================================================================
build_intel:
  stage: build 
  tags:
    - vm_linux
  only:
    - master
  before_script:
    - . ~/environments/modules_for_gvec_intel
  script: 
    - mkdir -f build__intel
    - cd build__intel; pwd
    - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_NETCDF=ON ../.
    - make
  after_script:
    - pwd 
  artifacts:
    name: "${CI_PIPELINE_ID}_${CI_BUILD_REF_NAME}_${CI_BUILD_NAME}"
    expire_in: 1 hour
    when: always
    paths:
    - build__intel


# =================================================================================================================================
# Stage "short_runs"
# =================================================================================================================================
short_runs_toksy:
  stage: short_runs
  tags:
    - vm_linux
  only:
    - master
  before_script:
    - . ~/environments/modules_for_gvec_intel
  script: 
    - cd ini/toksy; pwd
    - ../../build__intel/bin/gvec parameter.ini |tee log
  after_script:
    - pwd 
  artifacts:
    name: "${CI_PIPELINE_ID}_${CI_BUILD_REF_NAME}_${CI_BUILD_NAME}"
    expire_in: 1 hour
    when: always
    paths:
    - ini/toksy/*


