repos:
  # general hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer # ensure files end with a newline
      - id: trailing-whitespace # remove trailing whitespace
      - id: check-case-conflict # check for filenames that only differ by case
      - id: check-merge-conflict # check for merge conflict strings
      - id: check-added-large-files # prevent large files from being added
        args: ['--maxkb=4048', '--enforce-all']
        exclude: 'wout_d23p4_tm.nc'

  # automatic (python) code formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.3
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
        exclude: 'tools/|src/gvec_to_gene'
      # Run the formatter.
      - id: ruff-format
        exclude: 'tools/|src/gvec_to_gene'

  # cleaning jupyter notebooks
  - repo: https://github.com/srstevenson/nb-clean
    rev: 4.0.1
    hooks:
      - id: nb-clean
        args:
          - --remove-empty-cells
          - --remove-all-notebook-metadata
