# =================================================================================================================================
# Stage "build"
# =================================================================================================================================

spec:
  inputs:
    env:
      description: Name of the environment, e.g. `.mpcdfci_intel2023`
      default: .mpcdfci_intel2023
    vars:
      description: Template with variables or parallel:matrix
      default: .vars_matrix_build
    cmake-opts:
      description: Template with variables for CMake options
      default: .cmake_def_opts
    build-postfix:
      description: Job name postfix, e.g. `_only_converter`
      default: ""
    rules:
      description: Rules for the job, e.g. `.rules_default`
      default: .rules_default

---

build$[[ inputs.env ]]$[[ inputs.build-postfix ]]:
  stage: build
  extends:
    - $[[ inputs.env ]]
    - .before_script_modules
    - .script_build
    - $[[ inputs.cmake-opts ]]
    - $[[ inputs.vars ]]
    - $[[ inputs.rules ]]
  needs:
    - env$[[ inputs.env ]]
