# Copyright (c) 2025 GVEC Contributors, Max Planck Institute for Plasma Physics
# License: MIT
"""pyGVEC: A Python interface for the GVEC code."""

# _version.py is generated by setuptools_scm
try:
    from gvec._version import __version__, __version_tuple__
except ImportError:
    __version__ = "unknown"

# primary classes and functions

from gvec.state import State, load_state, find_state, find_states
from gvec.comp import (
    compute,
    evaluate,
    evaluate_sfl,
    Evaluations,
    EvaluationsBoozer,
    EvaluationsBoozerCustom,
)
from gvec.run import run, Run  # ToDo: shadows submodule

# submodules

from gvec import comp, fourier, quantities, scripts, state, surface, util
