#!/bin/bash
# bash source script for loading modules on mpcdf shared runner
# LAST MODIFIED: 2026-01-10
# ===========================================

module purge
module load git
module load cmake
module load nvhpcsdk
module load mkl
module load hdf5-serial
module load netcdf-serial
module load python-waterboa

module list
export CC=`which nvc`
export FC=`which nvfortran`
export CXX=`which nvc++`
