#!/bin/bash
# bash source script for loading modules on mpcdf shared runner
# LAST MODIFIED: 2026-01-10
# ===========================================

module purge
module load git
module load cmake
module load intel
module load impi
module load mkl
module load hdf5-serial
module load netcdf-serial
module load python-waterboa

module list
export FC=`which mpiifx`
export CC=`which mpiicx`
export CXX=`which mpiicx`
