#!/bin/bash

module purge
module load git
module load cmake
module load intel
module load impi
module load mkl
module load hdf5-serial
module load netcdf-serial
module load anaconda
#module load ftimings
module load numdiff
module list
export FC=`which mpiifort`
export CC=`which mpiicc`
export CXX=`which mpiicx`
