#!/bin/bash

module purge
module load cmake
module load gcc/9
module load openmpi/4
module load mkl
module load hdf5-serial
module load netcdf-serial
module load ftimings
module load numdiff
module list
export FC=`which mpif90`
