#!/bin/bash

# ===========================================
# use this setup on raven with the command:
# > . CI_setup/mpcdf_setup_nvfortran
#
# LAST MODIFIED: 2025-01-31
# ===========================================

module purge
module load git
module load git-lfs
module load cmake
module load nvhpcsdk/23
module load mkl
module load hdf5-serial
module load netcdf-serial
module load anaconda/3/2023.03 
#module load numdiff
module list
export CC=`which nvc`
export FC=`which nvfortran`
export CXX=`which nvc++`


