#!/bin/bash

module purge
module load git
module load cmake
module load gcc/9
module load mkl
module load hdf5-serial
module load netcdf-serial
module load ftimings
module load anaconda/3/2023.03  # for pytest
module list
export FC=`which gfortran`
