#!/bin/bash

module purge
module load git
module load git-lfs
module load cmake
module load gcc/12
module load openmpi/4
module load mkl
module load hdf5-serial
module load netcdf-serial
module load anaconda/3/2023.03 #for pytest
#module load ftimings
#module load numdiff
module list
export FC=`which mpif90`
