#!/bin/bash

module purge
module load git
module load git-lfs
module load cmake
module load intel/19.1.3
module load mkl/2020.4
module load hdf5-serial/1.10.7
module load netcdf-serial/4.7.0
module load anaconda/3/2023.03 #for pytest
#module load ftimings
module list
export FC=`which ifort`
export CC=`which icc`
export CXX=`which icc`
