#!/bin/bash

module purge
module load cmake
module load intel/19.1.3
module load mkl/2020.4
module load hdf5-serial/1.10.7
module load netcdf-serial/4.7.0
module load ftimings
module load numdiff
module load git
module list
export FC=`which ifort`
