#!/bin/bash
# bash source script for module setup on viper
#
# LAST MODIFIED: 2025-01-12
# ===========================================

module purge
module load git
module load cmake
module load gcc/15
module load mkl
module load hdf5-serial
module load netcdf-serial
module load ftimings
module load python-waterboa/2025.06

module list
export FC=`which gfortran`
export CC=`which gcc`
export CXX=`which g++`
