#!/bin/bash

# ===========================================
# use this setup on viper with the command:
# > . CI_setup/viper_setup_intel
#
# LAST MODIFIED: 2024-12-05
# ===========================================

module purge
module load git
module load git-lfs
module load cmake/3.30
module load intel/2024.0
module load mkl/2024.0
module load hdf5-serial/1.14.1
module load netcdf-serial/4.9.2
module load ftimings
module load anaconda/3/2023.03 #for pytest

module list
export FC=`which ifx`
export CC=`which icx`
export CXX=`which icx`
export CMAKE_EXECUTABLE=`which cmake`
